server:
  port: 9100

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fdp?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    database: mysql
    show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate-format_sql: true
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
        dialect: org.hibernate.dialect.MySQL57Dialect
        entitymanager:
          packagesToScan: org.ddd.yzf.entity
  mvc:
    date-format: yyyy-MM-dd

mybatis:
  mapper-locations:
    - classpath*:/mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback.xml #日志配置
  level:
    com:
      looedu:
        mapper: debug

sms:
  regexp:
    phone: "^[1](([3][0-9])|([4][5-9])|([5][0-3,5-9])|([6][5,6])|([7][0-8])|([8][0-9])|([9][1,8,9]))[0-9]{8}$"
  aliyun:
    accessKeyId: dddddddddddddddddddddddddddd
    accessKeySecret: ddddddddddddddddddddddddddddd
    signName: 教务管理系统
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com
    regionId: cn-hangzhou
    templateCode:
      verificationCode: SMS_111111111